### ISSUE TITLE
README gives incorrect static URL

### ISSUE THREAD

**Issue by skewty** [thingsboard/thingsboard-extensions#38]
README says to use `static/widgets/thingsboard-extension-widgets.js` but this value is what actually works `static/thingsboard-extension-widgets.js` ("widgets" folder must be removed from path).

**Comment by vvlladd28** [comment]
Hi @skewty,
Thank you for pointing out the error, we will fix it in the near future

**Comment by vvlladd28** [comment]
Hi @skewty, 
We are fixed in commit be5b0089d88711df01ee2acf3a2373c31e399e69
