### ISSUE TITLE
Failed to load module if we use it inside markdown card

### ISSUE THREAD

**Issue by dhaval2017** [thingsboard/thingsboard-extensions#42]
I tried to add custom widget in state and then added that state inside markdown card 

<tb-dashboard-state style="height:100%" [ctx]="ctx" stateId="test"></tb-dashboard-state>

when we use custom widgets in markdown card it gives error

![image](https://user-images.githubusercontent.com/33371842/200761363-872387be-a1db-4396-98de-752dccf16c7d.png)

**Comment by ChantsovaEkaterina** [comment]
Hello @dhaval2017 
This issue was fixed in TB version 3.4.4 (PR [#8013](https://github.com/thingsboard/thingsboard/pull/8013)).
