### ISSUE TITLE
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT -- dev mode no longer works

### ISSUE THREAD

**Issue by skewty** [thingsboard/thingsboard-extensions#48]
Things checked:

- dev build completed successfully as per README
- new widget resource added as module `http://localhost:5000/static/widgets/thingsboard-extension-widgets.js` as per README
- Loading http://localhost:5000/static/widgets/thingsboard-extension-widgets.js works fine.. It's a CORS issue.

It would seem CORS security was tightened up in defaults elsewhere.
It likely needs to allow localhost:5000 by default.

Where / how is this done?

**Comment by skewty** [comment]
Is this the relevant section in `/usr/share/thingsboard/conf/thingsboard.yml`?

```tml
# spring CORS configuration
spring.mvc.cors:
  mappings:
    # Intercept path
    "[/api/**]":
      #Comma-separated list of origins to allow. '*' allows all origins. When not set,CORS support is disabled.
      allowed-origin-patterns: "*"
      #Comma-separated list of methods to allow. '*' allows all methods.
      allowed-methods: "*"
      #Comma-separated list of headers to allow in a request. '*' allows all headers.
      allowed-headers: "*"
      #How long, in seconds, the response from a pre-flight request can be cached by clients.
      max-age: "1800"
      #Set whether credentials are supported. When not set, credentials are not supported.
      allow-credentials: "true"
```

I am just running a small dev system using the .deb file for installation and defaults.
I did not add an nginx proxy in between.

**Comment by skewty** [comment]
Is there an easy / temporary work around that can be done until this is resolved?

**Comment by skewty** [comment]
Is getting an extension development environment up and running something paid "support" will help with?

**Comment by skewty** [comment]
I messaged ThingsBoard asking about paid support for this and this is what I got back:

> The current request is not supported by our support. 
>
> The only one that I can offer it's custom development from our team as an additional service. 
> Please note custom development is available only for the PE version. 

So the answer is no. ThingsBoard does not support this repo, not even for money.

**Comment by thclark** [comment]
> I messaged ThingsBoard asking about paid support for this and this is what I got back:
> 
> > The current request is not supported by our support.
> > The only one that I can offer it's custom development from our team as an additional service.
> > Please note custom development is available only for the PE version.
> 
> So the answer is no. ThingsBoard does not support this repo, not even for money.

Thanks @skewty - sadly that seems like for my organisation, thingsboard will be a quick starter then we'll have to move rapidly away from it, because building widgets that look professional (MUI components instead of a bunch of cartoon buttons and gauges), is an absolute must.

**Comment by skewty** [comment]
I was able to get this working after installing Ubuntu 23.04.  I was not able to get it to work in Windows.
Try that. I can likely help if you run into some small speed bumps / hurdles.

**Comment by jnfDev** [comment]
Hi guys, If anyone is still facing this problem I found a workaround.

Open the file `builders/static-serve/index.js` and add this line of code at line 54:

````
res.setHeader('Access-Control-Allow-Methods', 'GET');
````

Here’s an image of how it should look after you complete the steps. Once you do this, restart your development server, and everything appears to be functioning correctly.

<img width="1357" alt="Image" src="https://github.com/user-attachments/assets/dea88865-7ffd-4a96-93cc-9ac34af03413" />
