### ISSUE TITLE
BUG - bad path for extension in docker 

### ISSUE THREAD

**Issue by loicHercogener** [thingsboard/thingsboard-extensions#57]
https://github.com/thingsboard/thingsboard-extensions/blame/a320b4da0072f43c2ca7d797503c7dfae4048b27/thingsboard-extension-docker/pom.xml#L29

It's not :
<extension.folder>/usr/share/thingsboard/extenstions</extension.folder>
but :
<extension.folder>/usr/share/thingsboard/extensions</extension.folder>

best regards
loïc HOURDIN

**Comment by vvlladd28** [comment]
Thank you for your report,
We have fixed this problem in commit e20e026696ced2d737527925af633af65ed8e6e5
