### ISSUE TITLE
Error When Adding Resource From UI

### ISSUE THREAD

**Issue by zelms** [thingsboard/thingsboard-extensions#76]
I've been attempting to create a custom widget using this library for a little bit now, with limited success. I'm able to create the "thingsboard-extension-widgets.js" file, and get it uploaded as a resource. Once I include the resource in my widget I get the following error:

```
Widget wasn't loaded due to the following errors:
Module 'moduleName' doesn't have default export!
```

I was able to get the resource working one time using the release-3.8 branch, but after another build it stopped working. I'm not making any changes to the code, but this issue still seems to persist. Any ideas on what a fix could be?

**Comment by vvlladd28** [comment]
Hi @zelms,

Could you please let us know which version of ThingsBoard you are using and from which branch the build was made?

**Comment by zelms** [comment]
My mistake for not including that originally. I am running TB community edition v3.7.0, and I'm experiencing this issue when using the release tag v3.7. I have also had similar results when using branches release-3.6.2, release-3.6-server, and release-3.8. Although there was one build of the release-3.8 branch that did work for me, but then after minor modifications it gave the same error again. Recloning the release-3.8 branch and building without modifications resulted in the same error I've been getting. I've been considering upgrading to TB v3.8, although since the release-3.8 branch gave the same error I'm unsure if an upgrade would fix the issue

**Comment by zelms** [comment]
I have discovered that if I select the module name from the drop down menu that appears when you click the resource input box in the widget resource menu, then things seem to work properly. If I type the resource name into this box, then it doesn't seem to work. Not sure why selecting it from the drop down menu is any different, but I'm glad something got it to work. Also, the drop down menu only shows up after you've selected "Is module" further adding to my confusion
